# Generated by Django 5.2.6 on 2025-11-13 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Кино', 'verbose_name_plural': 'Кино'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='typemovie',
            options={'verbose_name': 'Тип произведения', 'verbose_name_plural': 'Типы произведений'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='type_movie',
            new_name='Тип произведения',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='Название произведения',
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='Job_title',
        ),
        migrations.RemoveField(
            model_name='typemovie',
            name='type',
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year_of_release',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Год выхода'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typemovie',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typemovie',
            name='title',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='full_name',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies+', to='movies.artist'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies+', to='movies.artist'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies+', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text_review',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_title',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
