# Generated by Django 5.2.6 on 2025-11-20 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_artist_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
