# Generated by Django 5.2.6 on 2025-11-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_jobtitle_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre_title',
            new_name='title',
        ),
    ]
