# Generated by Django 5.2.6 on 2025-11-20 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_genre_title_genre_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2025)], verbose_name='Год выхода'),
        ),
    ]
