# Generated by Django 5.2.6 on 2025-11-20 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_year_of_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Тип произведения',
        ),
        migrations.AddField(
            model_name='movie',
            name='type_movie',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='movies.typemovie', verbose_name='Тип произведения'),
            preserve_default=False,
        ),
    ]
