# Generated by Django 5.2.6 on 2025-11-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_тип_произведения_movie_type_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type_movie',
        ),
    ]
