# Generated by Django 5.2.6 on 2025-11-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_type_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type_movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='Тип произведения',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='movies.typemovie'),
            preserve_default=False,
        ),
    ]
