# Generated by Django 5.2.6 on 2025-11-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_movie_тип_произведения_movie_type_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.typemovie'),
        ),
    ]
