# Generated by Django 5.2.6 on 2025-11-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_type_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type_movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.typemovie', verbose_name='Тип произведения'),
        ),
    ]
