# Generated by Django 5.2.6 on 2025-11-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_movie_type_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Название произведения',
        ),
        migrations.AddField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Название произведения'),
        ),
    ]
