# Generated by Django 5.2.6 on 2025-11-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_remove_review_название_произведения_review_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movies+', to='movies.artist', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movies+', to='movies.artist', verbose_name='Режиссеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movies+', to='movies.genre', verbose_name='Жанры'),
        ),
    ]
